apiVersion: v1
kind: ServiceAccount
metadata:
  name: swiftkube-dash
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: swiftkube-dash-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs:
  - create
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
   name: swiftkube-dash
subjects:
 - kind: ServiceAccount
   name: swiftkube-dash
   namespace: default
roleRef:
   kind: ClusterRole
   name: swiftkube-dash-role
   apiGroup: rbac.authorization.k8s.io
